apiVersion: v2
name: nasty-csi-driver
description: A Helm chart for NASty CSI Driver - providing NFS, NVMe-oF, and iSCSI storage for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.17.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "v0.17.3"

keywords:
  - storage
  - csi
  - nasty
  - nfs
  - nvmeof
  - iscsi

home: https://github.com/nasty-project/nasty-csi
sources:
  - https://github.com/nasty-project/nasty-csi

maintainers:
  - name: Bartosz Fenski
    email: fenio@debian.org
    url: https://github.com/fenio

icon: https://github.com/nasty-project/nasty-csi/raw/main/docs/nasty-logo.png
